PROYECTO INDIVIDUAL Nº1

Data Engineering

-- Se cargan las librerías necesarias

In [22]:
# Librería pandas
import pandas as pd

Se crean los DataFrames desde los datasets enviados por Henry

In [23]:
#Primero el archivo de Amazon Titles

Amazon_Titles = pd.read_csv(r'..\Datasets\amazon_prime_titles.csv', encoding = 'utf-8')
Amazon_Titles.head(10)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,113 min,"Comedy, Drama",A small fishing village must procure a local d...
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,NaN,74 min,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,"March 30, 2021",2014,NaN,69 min,Documentary,"Pink breaks the mold once again, bringing her ..."
4,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,"March 30, 2021",1989,NaN,45 min,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...
5,s6,Movie,Living With Dinosaurs,Paul Weiland,"Gregory Chisholm, Juliet Stevenson, Brian Hens...",United Kingdom,"March 30, 2021",1989,NaN,52 min,"Fantasy, Kids",The story unfolds in a an English seaside town...
6,s7,Movie,Hired Gun,Fran Strine,"Alice Cooper, Liberty DeVitto, Ray Parker Jr.,...",United States,"March 30, 2021",2017,NaN,98 min,"Documentary, Special Interest","They are the ""First Call, A-list"" musicians, j..."
7,s8,Movie,Grease Live!,"Thomas Kail, Alex Rudzinski","Julianne Hough, Aaron Tveit, Vanessa Hudgens, ...",United States,"March 30, 2021",2016,NaN,131 min,Comedy,"This honest, uncompromising comedy chronicles ..."
8,s9,Movie,Global Meltdown,Daniel Gilboy,"Michael Paré, Leanne Khol Young, Patrick J. Ma...",Canada,"March 30, 2021",2017,NaN,87 min,"Action, Science Fiction, Suspense",A helicopter pilot and an environmental scient...
9,s10,Movie,David's Mother,Robert Allan Ackerman,"Kirstie Alley, Sam Waterston, Stockard Channing",United States,"April 1, 2021",1994,NaN,92 min,Drama,Sally Goodson is a devoted mother to her autis...

In [14]:
# Archivo de Disney
Disney_Titles = pd.read_csv(r'..\Datasets\disney_plus_titles.csv', encoding = 'utf-8')
Disney_Titles.head(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Duck the Halls: A Mickey Mouse Christmas Special,"Alonso Ramirez Ramos, Dave Wasson","Chris Diamantopoulos, Tony Anselmo, Tress MacN...",NaN,"November 26, 2021",2016,TV-G,23 min,"Animation, Family",Join Mickey and the gang as they duck the halls!
1,s2,Movie,Ernest Saves Christmas,John Cherry,"Jim Varney, Noelle Parker, Douglas Seale",NaN,"November 26, 2021",1988,PG,91 min,Comedy,Santa Claus passes his magic bag to a new St. ...
2,s3,Movie,Ice Age: A Mammoth Christmas,Karen Disher,"Raymond Albert Romano, John Leguizamo, Denis L...",United States,"November 26, 2021",2011,TV-G,23 min,"Animation, Comedy, Family",Sid the Sloth is on Santa's naughty list.
3,s4,Movie,The Queen Family Singalong,Hamish Hamilton,"Darren Criss, Adam Lambert, Derek Hough, Alexa...",NaN,"November 26, 2021",2021,TV-PG,41 min,Musical,"This is real life, not just fantasy!"
4,s5,TV Show,The Beatles: Get Back,NaN,"John Lennon, Paul McCartney, George Harrison, ...",NaN,"November 25, 2021",2021,NaN,1 Season,"Docuseries, Historical, Music",A three-part documentary from Peter Jackson ca...

In [24]:
# Archivo de Hulu
Hulu_Titles = pd.read_csv(r'..\Datasets\hulu_titles.csv', encoding = 'utf-8')
Hulu_Titles.head(10)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Ricky Velez: Here's Everything,NaN,NaN,NaN,"October 24, 2021",2021,TV-MA,NaN,"Comedy, Stand Up",​Comedian Ricky Velez bares it all with his ho...
1,s2,Movie,Silent Night,NaN,NaN,NaN,"October 23, 2021",2020,NaN,94 min,"Crime, Drama, Thriller","Mark, a low end South London hitman recently r..."
2,s3,Movie,The Marksman,NaN,NaN,NaN,"October 23, 2021",2021,PG-13,108 min,"Action, Thriller",A hardened Arizona rancher tries to protect an...
3,s4,Movie,Gaia,NaN,NaN,NaN,"October 22, 2021",2021,R,97 min,Horror,A forest ranger and two survivalists with a cu...
4,s5,Movie,Settlers,NaN,NaN,NaN,"October 22, 2021",2021,NaN,104 min,"Science Fiction, Thriller",Mankind's earliest settlers on the Martian fro...
5,s6,TV Show,The Halloween Candy Magic Pet,NaN,NaN,NaN,"October 22, 2021",2021,NaN,1 Season,"Family, Kids",Join Mila and Morphle on a mystery-filled Hall...
6,s7,Movie,The Evil Next Door,NaN,NaN,NaN,"October 21, 2021",2020,NaN,88 min,"Horror, Thriller","New to her role as a stepmom, a young woman mo..."
7,s8,TV Show,The Next Thing You Eat,NaN,NaN,NaN,"October 21, 2021",2021,NaN,1 Season,"Cooking & Food, Documentaries, Lifestyle & Cul...",With the unique insights and experience of Ugl...
8,s9,TV Show,Queens,NaN,NaN,NaN,"October 20, 2021",2021,TV-14,1 Season,"Drama, Music",Four women in their 40s reunite for a chance t...
9,s10,TV Show,The Bachelorette,NaN,NaN,United States,"October 20, 2021",2003,TV-14,3 Seasons,"Reality, Romance",ABC's romance reality show lets one lucky lady...

In [25]:
# Archivo Neflix:
# Lo que se realiza primero es el paso del archivo JSON a CSV
dataframe=pd.read_json(r"..\Datasets\netflix_titles.json")
dataframe.to_csv(r"..\Datasets\netflix_titles.csv")

In [26]:
#Cargo el dataframe con el archivo generado
Netflix_Titles = pd.read_csv(r'..\Datasets\netflix_titles.csv', encoding = 'utf-8')
Netflix_Titles.head(5)

,Unnamed: 0,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

Realizo un analisis de los datos que existen para tener una noción sobre que tipo de trabajo realizar

In [27]:
# Para el caso de Amazon chequeo la información
Amazon_Titles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9668 entries, 0 to 9667
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       9668 non-null   object
 1   type          9668 non-null   object
 2   title         9668 non-null   object
 3   director      7586 non-null   object
 4   cast          8435 non-null   object
 5   country       672 non-null    object
 6   date_added    155 non-null    object
 7   release_year  9668 non-null   int64
 8   rating        9331 non-null   object
 9   duration      9668 non-null   object
 10  listed_in     9668 non-null   object
 11  description   9668 non-null   object
dtypes: int64(1), object(11)
memory usage: 906.5+ KB

In [28]:
# Reviso la cantidad de nulos existentes en este archivo
Amazon_Titles.isnull().sum()

show_id            0
type               0
title              0
director        2082
cast            1233
country         8996
date_added      9513
release_year       0
rating           337
duration           0
listed_in          0
description        0
dtype: int64

In [29]:
#Archivo de Disney
Disney_Titles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1450 entries, 0 to 1449
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       1450 non-null   object
 1   type          1450 non-null   object
 2   title         1450 non-null   object
 3   director      977 non-null    object
 4   cast          1260 non-null   object
 5   country       1231 non-null   object
 6   date_added    1447 non-null   object
 7   release_year  1450 non-null   int64
 8   rating        1447 non-null   object
 9   duration      1450 non-null   object
 10  listed_in     1450 non-null   object
 11  description   1450 non-null   object
dtypes: int64(1), object(11)
memory usage: 136.1+ KB

In [30]:
# Reviso la cantidad de nulos existenes
Disney_Titles.isnull().sum()

show_id           0
type              0
title             0
director        473
cast            190
country         219
date_added        3
release_year      0
rating            3
duration          0
listed_in         0
description       0
dtype: int64

In [31]:
#Archivo de Hulu
Hulu_Titles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3073 entries, 0 to 3072
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       3073 non-null   object
 1   type          3073 non-null   object
 2   title         3073 non-null   object
 3   director      3 non-null      object
 4   cast          0 non-null      float64
 5   country       1620 non-null   object
 6   date_added    3045 non-null   object
 7   release_year  3073 non-null   int64
 8   rating        2553 non-null   object
 9   duration      2594 non-null   object
 10  listed_in     3073 non-null   object
 11  description   3069 non-null   object
dtypes: float64(1), int64(1), object(10)
memory usage: 288.2+ KB

In [32]:
#Cantidad de datos nulos
Hulu_Titles.isnull().sum()

show_id            0
type               0
title              0
director        3070
cast            3073
country         1453
date_added        28
release_year       0
rating           520
duration         479
listed_in          0
description        4
dtype: int64

In [65]:
#Archivo Netflix
Netflix_Titles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    8807 non-null   int64
 1   show_id       8807 non-null   object
 2   type          8807 non-null   object
 3   title         8807 non-null   object
 4   director      6173 non-null   object
 5   cast          7982 non-null   object
 6   country       7976 non-null   object
 7   date_added    8797 non-null   object
 8   release_year  8807 non-null   int64
 9   rating        8803 non-null   object
 10  duration      8804 non-null   object
 11  listed_in     8807 non-null   object
 12  description   8807 non-null   object
dtypes: int64(2), object(11)
memory usage: 894.6+ KB

In [33]:
#Cantidad de datos nulos
Netflix_Titles.isnull().sum()

Unnamed: 0         0
show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

Considerando los tipos de datos existentes, donde no se encuentran valores, así como información separada por comas, se procederá a hacer un trabajo de ETL.

Comienzo generando una copia de los DF

In [34]:
Amazon_Titles_copy =Amazon_Titles.copy()
Disney_Titles_copy=Disney_Titles.copy()
Hulu_Titles_copy=Hulu_Titles.copy()
Netflix_Titles_copy= Netflix_Titles.copy()

In [35]:
#Realizo el agregado de una columna para cada DF creado. De esa manera puedo asignarle la plataforma
Amazon_Titles_copy['Plataforma'] = 'Amazon'
Disney_Titles_copy['Plataforma'] = 'Disney'
Hulu_Titles_copy['Plataforma'] = 'Hulu'
Netflix_Titles_copy['Plataforma'] = 'Netflix'

In [36]:
#Reemplao valores de campos vacíos en la columna duration solo para la información de Hulu y Netlix
Hulu_Titles_copy['duration'].fillna('Sin dato',inplace=True)
Netflix_Titles_copy['duration'].fillna('Sin dato',inplace=True)

In [37]:
#Genero una función que me permita dividir la columna duration
def separa_columna_duration(DF):
    DF['temporadas']=DF["duration"].apply(lambda i: i.split()[0] if i.split()[1]=='Seasons' else '0')
    DF['duracion_peliculas']= DF['duration'].apply(lambda i: i.split()[0] if i.split(" ",1)[1]=='min' or i.split(" ",1)[1]=='mim'  else '0')
    return DF

In [38]:
Amazon_Titles_copy =separa_columna_duration(Amazon_Titles_copy)
Disney_Titles_copy = separa_columna_duration(Disney_Titles_copy)
Hulu_Titles_copy = separa_columna_duration(Hulu_Titles_copy)
Netflix_Titles_copy = separa_columna_duration(Netflix_Titles_copy)

In [39]:
#Elimino la columna duration en cada archivo 
Amazon_Titles_copy.drop(columns='duration',inplace=True)
Disney_Titles_copy.drop(columns='duration',inplace= True)
Hulu_Titles_copy.drop(columns= 'duration', inplace=True)
Netflix_Titles_copy.drop(columns='duration',inplace=True)

In [40]:
#Chequeo la información
Amazon_Titles_copy.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,listed_in,description,Plataforma,temporadas,duracion_peliculas
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,"Comedy, Drama",A small fishing village must procure a local d...,Amazon,0,113
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,"Drama, International",A Metro Family decides to fight a Cyber Crimin...,Amazon,0,110
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,NaN,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...,Amazon,0,74
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,"March 30, 2021",2014,NaN,Documentary,"Pink breaks the mold once again, bringing her ...",Amazon,0,69
4,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,"March 30, 2021",1989,NaN,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...,Amazon,0,45

In [41]:
#Realizo la integración en un solo DF a fines practicos
peliculas_y_series=pd.concat([Amazon_Titles_copy,Disney_Titles_copy,Hulu_Titles_copy,Netflix_Titles_copy],axis=0)

In [42]:
#chequeo el Dataframe unico
peliculas_y_series.head(10)

,show_id,type,title,director,cast,country,date_added,release_year,rating,listed_in,description,Plataforma,temporadas,duracion_peliculas,Unnamed: 0
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,"Comedy, Drama",A small fishing village must procure a local d...,Amazon,0,113,NaN
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,"Drama, International",A Metro Family decides to fight a Cyber Crimin...,Amazon,0,110,NaN
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,NaN,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...,Amazon,0,74,NaN
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,"March 30, 2021",2014,NaN,Documentary,"Pink breaks the mold once again, bringing her ...",Amazon,0,69,NaN
4,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,"March 30, 2021",1989,NaN,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...,Amazon,0,45,NaN
5,s6,Movie,Living With Dinosaurs,Paul Weiland,"Gregory Chisholm, Juliet Stevenson, Brian Hens...",United Kingdom,"March 30, 2021",1989,NaN,"Fantasy, Kids",The story unfolds in a an English seaside town...,Amazon,0,52,NaN
6,s7,Movie,Hired Gun,Fran Strine,"Alice Cooper, Liberty DeVitto, Ray Parker Jr.,...",United States,"March 30, 2021",2017,NaN,"Documentary, Special Interest","They are the ""First Call, A-list"" musicians, j...",Amazon,0,98,NaN
7,s8,Movie,Grease Live!,"Thomas Kail, Alex Rudzinski","Julianne Hough, Aaron Tveit, Vanessa Hudgens, ...",United States,"March 30, 2021",2016,NaN,Comedy,"This honest, uncompromising comedy chronicles ...",Amazon,0,131,NaN
8,s9,Movie,Global Meltdown,Daniel Gilboy,"Michael Paré, Leanne Khol Young, Patrick J. Ma...",Canada,"March 30, 2021",2017,NaN,"Action, Science Fiction, Suspense",A helicopter pilot and an environmental scient...,Amazon,0,87,NaN
9,s10,Movie,David's Mother,Robert Allan Ackerman,"Kirstie Alley, Sam Waterston, Stockard Channing",United States,"April 1, 2021",1994,NaN,Drama,Sally Goodson is a devoted mother to her autis...,Amazon,0,92,NaN

In [43]:
#Elimino última columna adicional
peliculas_y_series.drop(columns='Unnamed: 0',inplace=True)

In [44]:
#chequeo el Dataframe con la columna eliminada
peliculas_y_series.head(10)

,show_id,type,title,director,cast,country,date_added,release_year,rating,listed_in,description,Plataforma,temporadas,duracion_peliculas
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,"Comedy, Drama",A small fishing village must procure a local d...,Amazon,0,113
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,"Drama, International",A Metro Family decides to fight a Cyber Crimin...,Amazon,0,110
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,NaN,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...,Amazon,0,74
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,"March 30, 2021",2014,NaN,Documentary,"Pink breaks the mold once again, bringing her ...",Amazon,0,69
4,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,"March 30, 2021",1989,NaN,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...,Amazon,0,45
5,s6,Movie,Living With Dinosaurs,Paul Weiland,"Gregory Chisholm, Juliet Stevenson, Brian Hens...",United Kingdom,"March 30, 2021",1989,NaN,"Fantasy, Kids",The story unfolds in a an English seaside town...,Amazon,0,52
6,s7,Movie,Hired Gun,Fran Strine,"Alice Cooper, Liberty DeVitto, Ray Parker Jr.,...",United States,"March 30, 2021",2017,NaN,"Documentary, Special Interest","They are the ""First Call, A-list"" musicians, j...",Amazon,0,98
7,s8,Movie,Grease Live!,"Thomas Kail, Alex Rudzinski","Julianne Hough, Aaron Tveit, Vanessa Hudgens, ...",United States,"March 30, 2021",2016,NaN,Comedy,"This honest, uncompromising comedy chronicles ...",Amazon,0,131
8,s9,Movie,Global Meltdown,Daniel Gilboy,"Michael Paré, Leanne Khol Young, Patrick J. Ma...",Canada,"March 30, 2021",2017,NaN,"Action, Science Fiction, Suspense",A helicopter pilot and an environmental scient...,Amazon,0,87
9,s10,Movie,David's Mother,Robert Allan Ackerman,"Kirstie Alley, Sam Waterston, Stockard Channing",United States,"April 1, 2021",1994,NaN,Drama,Sally Goodson is a devoted mother to her autis...,Amazon,0,92

In [45]:
#Modifico las letras a mayuscula
peliculas_y_series.columns=['Show_Id','Type','Title','Director','Cast','Country','Date_Added','Release_Year','Rating', 'Listed_In','Description','Plataform','Seasons','Movie_Duration']

In [62]:
#chequeo el Dataframe unico
peliculas_y_series.head(10)

,Show_Id,Type,Title,Director,Cast,Country,Date_Added,Release_Year,Rating,Listed_In,Description,Plataform,Seasons,Movie_Duration
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,"Comedy, Drama",A small fishing village must procure a local d...,Amazon,0,113
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,"Drama, International",A Metro Family decides to fight a Cyber Crimin...,Amazon,0,110
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,NaN,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...,Amazon,0,74
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,"March 30, 2021",2014,NaN,Documentary,"Pink breaks the mold once again, bringing her ...",Amazon,0,69
4,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,"March 30, 2021",1989,NaN,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...,Amazon,0,45
5,s6,Movie,Living With Dinosaurs,Paul Weiland,"Gregory Chisholm, Juliet Stevenson, Brian Hens...",United Kingdom,"March 30, 2021",1989,NaN,"Fantasy, Kids",The story unfolds in a an English seaside town...,Amazon,0,52
6,s7,Movie,Hired Gun,Fran Strine,"Alice Cooper, Liberty DeVitto, Ray Parker Jr.,...",United States,"March 30, 2021",2017,NaN,"Documentary, Special Interest","They are the ""First Call, A-list"" musicians, j...",Amazon,0,98
7,s8,Movie,Grease Live!,"Thomas Kail, Alex Rudzinski","Julianne Hough, Aaron Tveit, Vanessa Hudgens, ...",United States,"March 30, 2021",2016,NaN,Comedy,"This honest, uncompromising comedy chronicles ...",Amazon,0,131
8,s9,Movie,Global Meltdown,Daniel Gilboy,"Michael Paré, Leanne Khol Young, Patrick J. Ma...",Canada,"March 30, 2021",2017,NaN,"Action, Science Fiction, Suspense",A helicopter pilot and an environmental scient...,Amazon,0,87
9,s10,Movie,David's Mother,Robert Allan Ackerman,"Kirstie Alley, Sam Waterston, Stockard Channing",United States,"April 1, 2021",1994,NaN,Drama,Sally Goodson is a devoted mother to her autis...,Amazon,0,92

In [61]:
#Verifico la infrmación del DF creado
peliculas_y_series.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 22998 entries, 0 to 8806
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Show_Id         22998 non-null  object
 1   Type            22998 non-null  object
 2   Title           22998 non-null  object
 3   Director        14739 non-null  object
 4   Cast            17677 non-null  object
 5   Country         11499 non-null  object
 6   Date_Added      13444 non-null  object
 7   Release_Year    22998 non-null  int64
 8   Rating          22134 non-null  object
 9   Listed_In       22998 non-null  object
 10  Description     22994 non-null  object
 11  Plataform       22998 non-null  object
 12  Seasons         22998 non-null  int32
 13  Movie_Duration  22998 non-null  int32
dtypes: int32(2), int64(1), object(11)
memory usage: 2.5+ MB

In [48]:
#Transformar tipo de dato cantidad 
peliculas_y_series.Seasons=peliculas_y_series.Seasons.astype(int)

In [57]:
#Transformo el tipo de dato de duración
peliculas_y_series.Movie_Duration=peliculas_y_series.Movie_Duration.astype(int)

In [58]:
#Paso el archivo final a csv
peliculas_y_series.to_csv(r"..\Datasets\peliculas_y_series.csv", index=False, header=True)

Realizo la primer consulta
Máxima duración según tipo de film (película/serie), por plataforma y por año.

In [50]:
Data_Frame=peliculas_y_series[(peliculas_y_series['Release_Year']== 2018) & (peliculas_y_series['Plataform']== "Hulu")] #filtro por año y plataforma

In [51]:
a =Data_Frame.Movie_Duration.max()
Titulo = Data_Frame[Data_Frame.Movie_Duration==a]['Title']

In [52]:
Titulo=Titulo.to_list()

In [53]:
Titulo=Titulo[0]

In [54]:
Titulo

'The House That Jack Built'

Realizo la segunda consulta:
Cantidad de peliculas y series (separado) por plataforma

In [55]:
print("La cantidad es de: ", ((peliculas_y_series['Plataform']=='Netflix')&(peliculas_y_series['Type'].str.contains('Movie'))).sum(), ' peliculas')
print("La cantidad es de: ", ((peliculas_y_series['Plataform']=='Netflix')&(peliculas_y_series['Type'].str.contains('TV Show'))).sum(), ' series')

La cantidad es de:  6131  peliculas
La cantidad es de:  2676  series

Tercera consulta
Cantidad de veces que se repite un género

In [60]:
print("El género se repite: ",((peliculas_y_series['Listed_In'].str.contains('Comedy')) & (peliculas_y_series['Plataform']=='Amazon')).sum(),' veces')

El género se repite:  2099  veces